In [2]:
import sys
import numpy as np

In [6]:
a = np.array([1, 2, 9])

In [9]:
a[1]

2

In [17]:
b = np.array([1.2, 3.0, 0., 5.6])

In [16]:
b

array([1.2, 3. , 0. , 5.6])

In [13]:
b.dtype


dtype('int32')

In [14]:
a.dtype

dtype('int32')

In [18]:
b[3]

5.6

In [19]:
c = np.array([1, 2, 9] , dtype = np.float)
c #1-dimensional array

array([1., 2., 9.])

In [21]:
s = np.array([
    [1,3,5] , 
    [23,3,6]
])
s

array([[ 1,  3,  5],
       [23,  3,  6]])

In [22]:
s.shape

(2, 3)

In [23]:
s.ndim

2

In [24]:
s.size

6

In [25]:
d = np.array([
    [1,2,3] ,
    [4,5,6] ,
    [7,8,9]
])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
d[0]

array([1, 2, 3])

In [27]:
d[2][1]

8

In [29]:
d[1][0]

4

In [30]:
d[1,0] #[d1,d2,d3,d4,......]

4

In [31]:
d[2] = 10

In [32]:
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 10, 10]])

In [33]:
d[2]=10,1,2

In [34]:
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10,  1,  2]])

In [35]:
d.sum() #sum

34

In [36]:
d.mean() #mean

3.7777777777777777

In [37]:
d.std() #standard deviation

2.739739556875101

In [38]:
d.var() #variance

7.506172839506173

In [40]:
d.sum(axis =0) #column

array([15,  8, 11])

In [41]:
d.sum(axis =1) #row

array([ 6, 15, 13])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [18]:
np.ones([2,2] , dtype = np.int)

array([[1, 1],
       [1, 1]])

In [19]:
np.ones([3,2] , dtype = np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
x = np.arange(4 , dtype = np.int)
np.ones_like(x)

array([1, 1, 1, 1])

In [21]:
np.zeros_like(x)

array([0, 0, 0, 0])

In [22]:
np.ones([4,4] , dtype = np.int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [30]:
y = np.ones([3,4] , dtype = np.int)
np.ones_like(y)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.randint(10 , size=3)

array([5, 2, 3])

In [42]:
np.random.randn(3,3,3)

array([[[ 0.93779843, -0.42612551, -1.22446265],
        [-0.97342834,  0.98463355,  0.76699485],
        [-0.17238375, -1.43073815, -1.11455904]],

       [[ 0.21498812,  0.91675873,  1.7130558 ],
        [-0.07977576,  0.70792626, -1.94513969],
        [ 1.5020434 ,  0.50974318, -0.64437836]],

       [[ 0.76358445, -0.55734337,  0.74690153],
        [ 1.3877399 , -0.81752694, -1.87861817],
        [ 0.05508702,  0.66545877, -0.28777627]]])

In [45]:
q = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16],
    [45,  1, 12, 13]
])

In [56]:
q[1:-1,1:-1]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [57]:
q[:2,:2]

array([[1, 2],
       [5, 6]])

In [58]:
q[2:,2:]

array([[11, 12],
       [15, 16],
       [12, 13]])

In [59]:
q[-1,-1]=0

In [60]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [45,  1, 12,  0]])

In [61]:
q+5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [50,  6, 17,  5]])

In [62]:
w = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [63]:
bo = w>=0
bo

array([False,  True,  True, False,  True,  True,  True,  True, False,
        True])

In [65]:
w[bo]

array([ 2,  0,  5,  6,  0,  0, 10])

In [68]:
mn = w>=w.mean()
w[mn]

array([ 2,  5,  6, 10])

In [71]:
bm = (w==2) | (w==5)
w[bm]

array([2, 5])

In [72]:
w.all()  #TURE if every element of an array is not 0 otherwise FALSE

False

In [73]:
w.any()  #TRUE if any of the elements is non zero

True

In [74]:
w.sum()


9

In [76]:
q.sum(axis=0)

array([73, 33, 48, 40])

In [77]:
q.mean(axis =1)

array([ 2.5,  6.5, 10.5, 14.5, 14.5])

In [80]:
q.max()


45